### ISSUE TITLE
IMPORTANT: requiring contributors permission to move to core

### ISSUE THREAD

**Issue by ebrehault** [collective/collective.contentrules.mailtogroup#18]
Hello @fulv, @hvelarde, @mauritsvanrees, @kcleong, @prakharjoshi, @cekk,

You have contributed to this repository and we would like to move this feature to Plone core (see https://github.com/plone/Products.CMFPlone/issues/1808).
To do that we need your explicit permission.
So please drop a comment here to accept (or not).

Thanks you.

**Comment by hvelarde** [comment]
I grant you explicit permission over my work to move this feature to the Plone core.

**Comment by mauritsvanrees** [comment]
I give my permission.

**Comment by kcleong** [comment]
I give my permission

**Comment by cekk** [comment]
Sure, i give my permission!
I have only one doubt: as we discussed in #4, the adoption of plone.stringinterp removed two previous string replacements.
If we want to restore these features, i see three solutions:
- add the two substitutions directly in this package
- add the two substitutions in plone.stringinterp
- add dependencies to other packages (like collective.stringinterp.text)

If this will be merged in plone core, what's the best approach?

**Comment by fulv** [comment]
I grant you explicit permission over my work to move this feature to the
Plone core.

**Comment by gforcada** [comment]
@ebrehault github statistics pages only show one year worth of data, not the full history. According to ``git shortlog -sn`` these are **all** the contributors:

``
    17  Fulvio Casali
    13  Kim Chee Leong
    10  hvelarde
     7  ida
     6  Kim Chee Loeng
     5  Maurits van Rees
     5  WouterVH
     4  gww
     2  Peter Uittenbroek
     1  Andrea Cecchi
     1  Héctor Velarde
     1  prakhar
``
So we are missing:
```
     7  ida
     5  WouterVH
     4  gww
     2  Peter Uittenbroek
```

So that would be @idgserpro @WouterVH @puittenbroek and gww... any idea of his github handle? He did the first few commits of the package...

**Comment by davisagli** [comment]
gww might be someone working for Goldmund, Wyldebeast & Wunderliebe?

**Comment by fulv** [comment]
With respect to @cekk 's question, re: #4, my vote would be to add those two substitutions to plone.stringinterp.  Does that need its own PLIP?

**Comment by idgserpro** [comment]
It's not me. I did not contribute to this project.

**Comment by puittenbroek** [comment]
Peter Uittenbroek, that's me indeed :)
gww, you can put under Kim Chee @kcleong , I believe he made the initial product IIRC when working for us (GWW -> Goldmund, Wyldebeast & Wunderliebe).

**Comment by puittenbroek** [comment]
ida is https://github.com/ida ?

**Comment by ida** [comment]
Oh Hi Peter, thanks for pinging. Yeah sure, if there's anything left of my contributions, happily giving permission.

**Comment by prakharjoshi** [comment]
I give my permission over my work to move this feature to the Plone core. It will be a great pleasure.

**Comment by gforcada** [comment]
@puittenbroek you seemed to miss to state if you accept (or not) to move your contributions to core. :-)

**Comment by puittenbroek** [comment]
Ah apologies, I missed that :)

I give my permission!

**Comment by ida** [comment]
@fulv Could you (or another owner) remove me of the owner's list, please? It would also be awesome, if someone could leave a note in the README, that vs. 1.3.1 is able to send an item's text-field via mail, and following versions currently cannot. I'd do it myself, but don't have commit-permissions anymore in the collective since the switch from SVN to GIT, and don't intend to regain it. TIA, Ida

**Comment by fulv** [comment]
@ida I've removed you from the owners.  As for the note in the README, it won't be visible in the package until the next release.  But hopefully I'll get around to fixing the issue by then.

**Comment by ida** [comment]
@fulv Thank you very much! BTW, is the core-merge ment for Plone-5 only, or also for Plone-4?

**Comment by fulv** [comment]
Only Plone 5.

**Comment by ida** [comment]
@fulv That's good to know, thank you and good proceeding!

**Comment by WouterVH** [comment]
I give my permission.

**Comment by ida** [comment]
@fulv Added the info in README, can you please an info-only release, so it shows up on pypi? Or re-grant ownership to my user, if you're too busy right now :-)

**Comment by ida** [comment]
:D thanks, now commited (entered password wrongly and headed right to the coffe-machine without noticing).

**Comment by ida** [comment]
Hm, was not noticing the err-msg after pushing:
"remote: error: Required status check "continuous-integration/travis-ci" is expected."
Haven't seen that before, do you know what it means?

**Comment by ida** [comment]
Ah:
"Basically this means that all developers must always do all development on their own branches, push those branches to Github, wait until tests pass, and only then can they run git merge and git push from their own local repositories."
Source: https://mariadb.org/protected-branches-ensuring-code-quality-git/
Gonna make a branch...

**Comment by ida** [comment]
@fulv Travis is on it: https://github.com/collective/collective.contentrules.mailtogroup/pull/20

**Comment by rileydog** [comment]
It seems everyone has agreed.  will this be part of Plone 6.0.x?

**Comment by ida** [comment]
@rileydog According to the referring [PLIP](https://github.com/plone/Products.CMFPlone/issues/1808) nothing ever happened, since this add-on was declared discontinued seven years ago.
