### ISSUE TITLE
with this installed, can't create content in Plone 5.1.0.1 (5110) 

### ISSUE THREAD

**Issue by rileydog** [collective/collective.contentrules.mailtogroup#19]
![screenshot 23](https://user-images.githubusercontent.com/1693063/38167852-5deea232-34f2-11e8-8b95-34769516e017.png)

selecting the Plone "Add" gives this blank screen.

After removing product from buildout and rebuild, and restart.  Plone returns to normal.  Did this twice to confirm.

**Comment by pbauer** [comment]
@rileydog I think this may be the same issue as https://github.com/plone/Products.CMFPlone/issues/2338 because this package has a dependey on plone.app.form. Try the solution specified there.

**Comment by rileydog** [comment]
@pbauer  thanks a lot.  The above link solved the problem.

thanks!

**Comment by ida** [comment]
closing as solved.
