### ISSUE TITLE
Error loading the content rule in Plone 5

### ISSUE THREAD

**Issue by rileydog** [collective/collective.contentrules.mailtogroup#6]
Product installs in P5 without issue, rule appears in rule pulldown list; however, From within Plone content rules, when I tried to use your product, I got a  pop up with error message:
##  "there was an error loading modal"

I originally raised this issue here, and discussion has some useful information here: 

https://community.plone.org/t/using-plone-rules-to-send-emails-to-users-based-on-roles/1275/6

**Comment by rileydog** [comment]
Here is some further information that might help.  this is from the zope logs:
2015-11-28T21:39:41 ERROR Zope.SiteErrorLog 1448746781.350.215994612666 http://mckennariley.webfactional.com/DocentIMS/++rule++rule-1/+action/plone.actions.MailGroup
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module z3c.form.form, line 218, in __call__
  Module plone.z3cform.fieldsets.extensible, line 58, in update
  Module plone.autoform.form, line 33, in updateFields
  Module plone.autoform.base, line 54, in updateFieldsFromSchemata
  Module plone.autoform.form, line 22, in schema
NotImplementedError: The class deriving from AutoExtensibleForm must have a 'schema' property
----

**Comment by fulv** [comment]
Release 1.6 with Plone 5 compatibility is now available on Pypi:  https://pypi.python.org/pypi/collective.contentrules.mailtogroup/1.6
