### ISSUE TITLE
No profile folder ?

### ISSUE THREAD

**Issue by prakharjoshi** [collective/collective.contentrules.mailtogroup#7]
Just curious as I can't find a profile folder for that add-on as I have always found a profile folder for any add-on in plone. Also how this add-on is installed in the plone site as what goes behind the scene when we add this add-on and restart the plone instance ?

**Comment by fulv** [comment]
Good question:  the readme says _No (generic setup) installation is necessary, the action is registered using ZCML._  Indeed, if you follow the inclusion trail from the main `configure.zcml` you see what happens.
I suggest perhaps search for other packages that provide custom content rules, and see if they do anything different.

**Comment by cewing** [comment]
@prakharjoshi it appears to me that there isn't anything installed by this package that requires a GenericSetup profile import to work.  In other words, simply adding this package to your buildout and re-starting is enough to make all of its functionality available.  This can happen when all the features a package provides are registered entirely in ZCML, as is the case here.  There just isn't anything that requires setup beyond ZCML.

**Comment by ida** [comment]
@prakharjoshi This addon will be installed for all Plonsites of a ZOPE-instance. You are right, to have a separation and bind it to an addons-specific-interface would be better :)
BTW, if you want to send the rich-text-field, too, you'll need to take vs. 1.3.1, not the newest one, due to #4. Best regards, Ida

**Comment by fulv** [comment]
@prakharjoshi I believe your question was answered, so I'm closing this issue.  Feel free to open other issues as you work on this.  Thanks!
