### ISSUE TITLE
Incorporate this group mailing into Plone core email notification

### ISSUE THREAD

**Issue by rileydog** [collective/collective.contentrules.mailtogroup#8]
I am working with a programmer to bring the ability to email to group in plone 5.  I can think of two ways: 
1) simply update this product  to P5, or 2) create a product that adds group mailing functionality  to Plone.
2)  I am not a programmer, so I don't know if the second approach is possible.  However, I did look int the code of this product and found, in addition to the code to create the email, etc, the following code that gets email addresses for users and groups:
---

```
members = schema.List(
    title = _(u"User(s) to mail"),
    description = _("The members where you want to send the e-mail message."),
    value_type = schema.Choice(source=UsersSource),
    required = False
    )

groups = schema.List(
    title = _(u"Group(s) to mail"),
    description = _("The group where you want to send this message. All \
        members of the group will receive an email."),
    value_type = schema.Choice(source=GroupsSource),
    required = False
    )
```
---

Could the group code be added to the core plone code via a product?  Would this provide the functionality I seek?  Seems too easy.  Note: would need to either change the existing interface to add entry box for listing groups, or keep form as is and allow intermingling of users, emails, and groups and the code would differentiate.
If so, we could create product that added the code to the existing Plone content rule to allow mail to group.  So the Plone world would have a separate product that gives them important functionality today and Plone managers could incorporate at some time if they wanted to 
the reason I like this approach is I know from experience that the plone built-in mailing works.  Looking at the mail to group product I see two bugs and don't know how important they are.  I've never actually used this mailtogroup (probably not smart of me), and I don't want to have to deal with bugs.
Thoughts and ideas?

**Comment by fulv** [comment]
It should be possible to make this (or another) add-on override the default plone mail action.

@prakharjoshi, please take a look at https://github.com/plone/plone.app.contentrules/blob/master/plone/app/contentrules/actions/configure.zcml#L197

**Comment by rileydog** [comment]
@prakharjoshi   Please post updates as you make some progress so I'll know what is happening

**Comment by prakharjoshi** [comment]
@fulv  Yeah that sounds good, but I have a doubt as we can see here https://github.com/collective/collective.contentrules.mailtogroup/blob/master/collective/contentrules/mailtogroup/actions/configure.zcml#L29 that we have a mail action for groups and the link you showed have a mail action for triggered objects so as we need to mail to groups so we can create a action here which uses this(p.a.contenttype) action and we can override the schema and factory so that it works for group and not a single trigger, right ?

**Comment by prakharjoshi** [comment]
@rileydog  Yeah sure, before starting working its always better to discuss the ways which can be better to choose :)

**Comment by rileydog** [comment]
@prakharjoshi   Any progress?

**Comment by prakharjoshi** [comment]
@rileydog  Sorry was kind of busy these days. I will update you as soon as possible. Will start working on it from tomorrow mostly :)

**Comment by fulv** [comment]
@prakharjoshi:  I'm not sure that the `event="zope.component.interfaces.IObjectEvent"` is necessary, I think it can be dropped.  If you look at the code in `plone.app.contentrules` it doesn't really care what type of event it is.
I think the `<plone:ruleAction` zcml slug can be changed to have the same name like the one in `plone.app.contentrules`.  I'm not sure if it will complain, or if that's all it will take to override.  Unfortunately, I don't think the `<plone:ruleAction` directive supports the `layer` attribute:
https://github.com/plone/plone.contentrules/blob/master/plone/contentrules/rule/metaconfigure.py

**Comment by prakharjoshi** [comment]
@fulv I tried to install the add-on to plone 5 instance and its showing schema not found in the logs... So may be we should add schema for this add-on ?

**Comment by prakharjoshi** [comment]
@fulv  Just to discuss is that the way we should do as shown in link http://ale-rt.github.io/posts/how-to-port-plone4-portlets-to-plone5.html ?

**Comment by prakharjoshi** [comment]
@rileydog  @fulv  Any ideas about the above suggestion to add a schema in the forms ?

**Comment by rileydog** [comment]
@fulv @prakharjoshi 
   I don't know if this is the right code, fulvio would.  My comment would be it doesn't have to differentiate between P4 and P5, as the existing code already works on P4.

**Comment by fulv** [comment]
@prakharjoshi Sorry, I've fallen behind in my github emails!

The reason it does not work in P5 is that it uses formlib instead of z3c.form.  So ale-rt's blog goes in the right direction, but I have not read it to know whether it has all the answers.  More likely, do a google search for migrating Plone control panels from formlib to z3c.form.  Basically, this is the core of the work this add-on requires to become P5-compatible.  Once that's done, it will work both in P4 and P5.

I can post some other links tomorrow if you don't find anything.

**Comment by prakharjoshi** [comment]
@fulv  Thanks for guiding me to the right direction, I will look up for the conversion of control panels from formlibs to z3cforms. As far as I have searched about that I came to know about that its the schema that is missing in current control panel form.

**Comment by fulv** [comment]
@prakharjoshi Take a look at this:  https://community.plone.org/t/plone-app-controlpanel-form-imports-on-plone-5/1208

**Comment by rileydog** [comment]
Hi folks,  not sure the direction this is taking (which is fine).  I would like to clarify what I am looking for.
1) if possible, simply make the existing "email to person"  in P5 action, have a section in the config form where a group can be added.  This is ideal in that you don't need to learn anything new.  the config form would be modified to include a input box for groups (ideally list driven by exising groups).  I see above some talk and I don't know if you are saying this can't be done.  If can't, fulvio, when you get a chance can you briefly explain why (I just like to understand)
2) if above not possible, why not just take the existing product "mail to group" and update the form to P5?
3) finally, the attached screen shot shows how "mail to group" , when installed, is displayed to user.  (note: problem is obviously that it doesn't work in P5.
4) I would like to be able to use this in the next two weeks.  Do you think this is possible?
![email to group](https://cloud.githubusercontent.com/assets/1693063/12733904/42bbc012-c8f2-11e5-8f33-af94fb2e5cce.png)

**Comment by fulv** [comment]
@rileydog, no, I'm not saying it can't be done.  I was just pointing to
what needs to be done to make it happen.

Formlib is the very, very old form library that was in use by Plone for
many, many versions.  A form library is what allows you to write Python
code that produces html forms, and handle the form submissions. For
example, these forms can be auto-generated for content types, or as in our
case, for control panels.
A newer form library, z3c.form, was introduced at some point (pypi says in
2007), and gained favor in the Plone world.  z3c.form was already used in
Plone 4 in many places, but the control panels were a formlib holdout.
One of the big changes in Plone 5 is that formlib was completely removed,
and z3c.form won.  That is one of the (many) things that causes old add-ons
to be incompatible with P5.

So this add-on needs to be converted to z3c.form, no matter what, period.
That's most of what this is all about.

The additional idea of making this add-on override the mail action in
content rules cannot be done without first converting to z3c.form.  You may
think that just because it works in Plone 4 we can have it replace/override
the default mail action and be done with it, but that's not how it works.

The conversion is not that hard, the override part I'm not so sure about.
Between Prakhar and myself, I think we can make this work in two weeks.

**Comment by rileydog** [comment]
thanks for the update.  
This will be an important content rule when you two get it working.

**Comment by prakharjoshi** [comment]
@fulv  yeah in 2 weeks we will convert it from formlib to z3c.forms :) . And thanks for such a great explanation. I also agree with @fulv  as we should first convert the add-on to z3c.forms and then do some other work. :)

**Comment by rileydog** [comment]
hi prakharjoshi, are you making progress on the conversion?

**Comment by fulv** [comment]
@rileydog sorry, I'm afraid I'm the bottleneck.  I'll get to it, I promise!

**Comment by prakharjoshi** [comment]
@rileydog  Yeah I created a pull request, After adding schema it was working fine on my local in P5, but travis is not happy with it as we can see here https://github.com/collective/collective.contentrules.mailtogroup/pull/9 , I think there are some dependencies that I am missing. I have asked fulvo to look into that, He is busy these days, once he is free we will start work again :)

**Comment by rileydog** [comment]
@fulv   @prakharjoshi 

Fulvio,  I forgot you are working on a launch.   This can wait until that is done.  Hope it goes well

**Comment by rileydog** [comment]
Not sure if I asked to allow multiple groups to be on the email notifications.  let me know if that is an issue.

**Comment by prakharjoshi** [comment]
@rileydog  Can you just try the new branch that I created, though its breaking the travis due to some dependencies but I was able to create a group to send mail. So it will be great if you can give it a try :)

**Comment by rileydog** [comment]
Hi. Don't know if I already replied to you 
   Where is the product for me to test. I don't know how to go to GitHub for a branch. 
    Can you install it for me ?
     Ssh details
          Docentims.com 
           Mckennariley
            267622!Wa

The app is plone5_test

___________________
Thanks, 

Wayne Glover 
(Sent from my iPhone)

**Comment by rileydog** [comment]
@prakharjoshi  I sent you an email a few days ago explaining I didn't know how to install it, but would be gald to test if you installed.  I included login credentials.   You haven't installed it yet, so I can't test.  when will you install it?

**Comment by rileydog** [comment]
@prakharjoshi 
   Since this approach isn't working (and I know I was the one who suggested it)
  why not just convert the P4 product to P5?  the only issue, I'm told, would be the form.  that should be much easier.

**Comment by rileydog** [comment]
@prakharjoshi 
  
I appreciate you trying; however,  this project is obviously dead.   I will have to try another approach to this as this is impacting a project of mine.
Please consider this project closed.

**Comment by fulv** [comment]
Hey @rileydog, please try adding this line to your buildout under `[sources]`:

```
collective.contentrules.mailtogroup = git git@github.com:collective/collective.contentrules.mailtogroup.git branch=add_schema
```

**Comment by prakharjoshi** [comment]
Ah!! @fulv  I was missing that as how to make my branch workable there instead of master in the production. Thanks for that. 

@rileydog  Sorry for delay but yeah try to install this add-on with this branch and it will gonna work fine I guess.

**Comment by prakharjoshi** [comment]
@fulv I think we should update the dependencies also as there are come conflicts in dependencies between travis and buildouts for this add-on, right ?

**Comment by rileydog** [comment]
OK,

I don't know how to do that. see attached buildout. I added the [instance]  
then the code you sent and got error:
"missing option: instance:recipe"

I will send you login credentials directly to your emails

havin' fun in Italy?

wayne


On Sat, 02 Apr 2016 03:15:21 -0700, Fulvio Casali  
<notifications@github.com> wrote:

> collective.contentrules.mailtogroup = git  
> git@github.com:collective/collective.contentrules.mailtogroup.git  
> branch=add_schema



-- 
_______________

Thanks,

Wayne Glover

**Comment by fulv** [comment]
I've submitted a PLIP:  https://github.com/plone/Products.CMFPlone/issues/1808

Further, with the 1.6 release, I think we can close this issue.
https://pypi.python.org/pypi/collective.contentrules.mailtogroup/1.6
